apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: healthcare/payment-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: MYSQL_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: PAYMENT_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: healthcare-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: healthcare-secret
                  key: MYSQL_PASSWORD
