apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  AUTH_DB: auth_db
  PATIENT_DB: patient_db
  DOCTOR_DB: doctor_db
  APPOINTMENT_DB: appointment_db
  PAYMENT_DB: payment_db
  NOTIFICATION_DB: notification_db
  AI_SYMPTOM_CHECKER_DB: ai_symptom_checker_db
  TELEMEDICINE_DB: telemedicine_db
  AUTH_SERVICE_URL: http://auth-service:8081
  PATIENT_SERVICE_URL: http://patient-service:8082
  DOCTOR_SERVICE_URL: http://doctor-service:8083
  APPOINTMENT_SERVICE_URL: http://appointment-service:8084
  PAYMENT_SERVICE_URL: http://payment-service:8085
  NOTIFICATION_SERVICE_URL: http://notification-service:8086
  AI_SYMPTOM_CHECKER_SERVICE_URL: http://ai-symptom-checker-service:8087
  TELEMEDICINE_SERVICE_URL: http://telemedicine-service:8088
