spring.application.name=ai-symptom-checker-service
server.port=${SERVER_PORT:8087}

PATIENT_SERVICE_URL=${PATIENT_SERVICE_URL:http://localhost:8082}
DOCTOR_SERVICE_URL=${DOCTOR_SERVICE_URL:http://localhost:8083}

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
