apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: healthcare/gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: AUTH_SERVICE_URL
            - name: PATIENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: PATIENT_SERVICE_URL
            - name: DOCTOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: DOCTOR_SERVICE_URL
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: APPOINTMENT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: PAYMENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: NOTIFICATION_SERVICE_URL
            - name: AI_SYMPTOM_CHECKER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: AI_SYMPTOM_CHECKER_SERVICE_URL
            - name: TELEMEDICINE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: TELEMEDICINE_SERVICE_URL
