apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: healthcare/notification-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: AUTH_SERVICE_URL
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: APPOINTMENT_SERVICE_URL
